print("This program will write a letter to a friend of yours!")
month = input("Let's start with the date. What is the month? Please enter a value from 1-12: ")
day = input("Great! What is the day? Please enter a value from 1-31: ")
year = input("Finnaly, what year is it? ")
name = input("Great! What is your friend's name? ")
named = input("What is your name? ")
message = input("What would you like to tell your friend? ")
print("Here is a draft of your letter to your friend:")
print(f"{(str(f'{month:0>2}' + "/" + f'{day:0>2}' + "/" + year).lstrip()):^255}")
print("Dear " + name + ",")
print("\t", message,"\n")
print("Signed!")
print(named)
